function [fitresult, gof] = createFit1(U, h2)
%CREATEFIT1(U,H2)
%  Create a fit.
%
%  Data for 'H1 graph' fit:
%      X Input: U
%      Y Output: h2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2023 15:14:27


%% Fit: 'H1 graph'.
[xData, yData] = prepareCurveData( U, h2 );

% Set up fittype and options.
ft = fittype( 'log' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'H1 graph' );
h = plot( fitresult, xData, yData );
legend( h, 'h2 vs. U', 'H1 graph', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'U', 'Interpreter', 'none' );
ylabel( 'h2', 'Interpreter', 'none' );
grid on


